<?php
/**
 * Copyright ePay | Dit Online Betalingssystem, (c) 2010.
 * 
 * This program is free software. You are allowed to use the software but NOT allowed to modify the software. 
 * It is also not legal to do any changes to the software and distribute it in your own name / brand. 
 */
 
//
// Load the epay standard object
//
$standard = Mage::getModel('epay/standard');

//
// Fetch order invoice info
//
$order = Mage::getModel('sales/order');
$order->loadByIncrementId($standard->getCheckout()->getLastRealOrderId());
//$order->sendNewOrderEmail();

//
// If integrated is not set something is wrong - throw exception then
//
if ($standard->getConfigData('integrated', $order ? $order->getStoreId() : null) != '1') {
	throw new exception("Invalid integrated type!?!?");
}

//
// Which payment types are enabled
//
function paymentTypeEnabled($type, $order) {
	$standard = Mage::getModel('epay/standard');
	$paymentTypeArray = explode(',', $standard->getConfigData('paymentoptionsintegratedlayout', $order ? $order->getStoreId() : null));
	foreach($paymentTypeArray as $item) if ($item == $type) return true;
  return false;
}

//
// Checks if only ordinary payments is enabled
//
function paymentsEnabledOnly($paymentMethod, $order) {
	$standard = Mage::getModel('epay/standard');
	$paymentTypeArray = explode(',', $standard->getConfigData('paymentoptionsintegratedlayout', $order ? $order->getStoreId() : null));
	foreach($paymentTypeArray as $item) if ($item != $paymentMethod) return false;
  return true;
}

//
// Extract the firstly paymentmethod selected in the list of integrated payment methods (0, 17, 20, 21, 22)
//
function getFirstSelectedPaymentMethod($order) {
	$res = 0;
	$standard = Mage::getModel('epay/standard');
	$paymentTypeArray = explode(',', $standard->getConfigData('paymentoptionsintegratedlayout', $order ? $order->getStoreId() : null));
	foreach($paymentTypeArray as $item) { 
		$res = $item; 
		break; 
	}
	return $res;
}

//
// Bool set to true when the first enabled integrated payment type is found
//
$paymentTypeFound = false;
?>
<style type="text/css">
#overlay {
    width: 100%;
    min-height: 100%;
    position: fixed;
    top: 0;
    left: 0;
    z-index: 400;
	background-color: #a7a7a7;
	filter:alpha(opacity=50);-moz-opacity:.50;opacity:.50;
    display: none;
    text-align: center;
}

#please_wait{
	display: none;
	font-size: 14px;
	background-color: #ffffff;
	left: 50%; margin-left: -175px; margin-top: -50px; height: 100px; position: fixed; top: 50%; width: 250px; display: none;
	z-index: 1000;
	text-align: center;
	border: 1px solid #a7a7a7;
}

#please_wait .please_wait_content{
	margin-top: 15px;
}

.dotWait {
	font-size: 18px;
}
</style>

<div id="overlay"></div>

<div id="please_wait">
	<div class="please_wait_content">
	<?php echo $this->__('EPAY_LABEL_102');  ?>
	<br />
	<span class="dotWait" id="dotWait" name="dotWait"></span></div>
</div>

<form method="post" action="https://ssl.ditonlinebetalingssystem.dk/auth/default.aspx" autocomplete="off" name="epay" id="epay">
	<input type="hidden" name="selectedpaymenttype" value="<?php echo getFirstSelectedPaymentMethod($order); ?>">


<?php
//
// Payment error - display message to the user
//
if (isset($_GET['error']) && isset($_GET['errortext'])) {
?>
		<div class="title"><?php echo $this->__('EPAY_LABEL_6') . " " . $_GET['error'] ?></div>
		<div style="border:solid 1px #ff0000; margin-left:15px; padding:10px; background-color:#faebe7;"><?php echo mb_convert_encoding(urldecode($_GET['errortext']), 'UTF-8', 'ISO-8859-1'); ?></div>
<?php	
}
?>

		<div id="paymenttype-0" style="display: <?php echo (!$paymentTypeFound && (($paymentTypeFound = paymentTypeEnabled(0, $order)))) ? 'block' : 'none'; ?>;">
			
            <div class="title checkout"><?php echo $this->__('Payment'); ?></div>
            <div class="content checkout left">
                <div class="title"><?php echo $this->__('Card'); ?></div>
                <div class="card" style="text-align:center; padding-left:20px; padding-top:20px;">
                    <span>
                        <img src="<?php echo $this->getSkinUrl('images/epay/visa.gif') ?>" border="0" title="VISA" />&nbsp;&nbsp;
                        <img src="<?php echo $this->getSkinUrl('images/epay/mastercard.gif') ?>" border="0" title="MasterCard" />&nbsp;&nbsp;
                        <img src="<?php echo $this->getSkinUrl('images/epay/dankort.gif') ?>" border="0" title="Dankort" />&nbsp;&nbsp;
                    </span>
                </div>

                <div class="lblock"><?php echo $this->__('EPAY_LABEL_9') ?></div><input name="cardno" id="cardno" title="<?php echo $this->__('EPAY_LABEL_9') ?>" value="" class="rblock required-entry input-text validate-digits validate-length minimum-length-16 maximum-length-16" style="width: 154px;" type="text" maxlength="30" />

                <div class="lblock"><?php echo $this->__('EPAY_LABEL_13') ?></div><input name="cvc" id="cvc" title="<?php echo $this->__('EPAY_LABEL_13') ?>" value="" class="cvc input-text<?php echo ($standard->getConfigData('integratedcardnovalidation', $order ? $order->getStoreId() : null) ? ' required-entry validate-digits validate-length minimum-length-3 maximum-length-4 ' : ''); ?>" type="text" maxlength="4"  style="width: 53px;" />

                <div class="lblock"><?php echo $this->__('Expiration'); //Udløbsdato ?></div>
                <div style="float:left;padding-bottom: 10px;">
                    <span style="float:left;width: 75px;">
                        <select id="epay_expiration"  class="month validate-cc-exp required-entry">
                            <option disabled>Choose</option>
                            <option>01</option>
                            <option>02</option>
                            <option>03</option>
                            <option>04</option>
                            <option>05</option>
                            <option>06</option>
                            <option>07</option>
                            <option>08</option>
                            <option>09</option>
                            <option>10</option>
                            <option>11</option>
                            <option>12</option>
                        </select>
                    </span> / 
                    <span style="width: 75px;">
                        <select id="epay_expiration_yr" class="year required-entry">
                            <option disabled>Choose</option>
                            <option>2012</option>
                            <option>2013</option>
                            <option>2014</option>
                            <option>2015</option>
                            <option>2016</option>
                            <option>2017</option>
                            <option>2018</option>
                            <option>2019</option>
                            <option>2020</option>
                        </select>
                    </span>
                </div>
                <div class="notice"><span class="red">*</span><?php echo $this->__('Aenean eu leo quam. Pellentesque ornare sem lacinia. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.') ?></div>
            </div>
        <div class="content checkout right">
            <div class="title"><?php echo $this->__('EPAY_LABEL_36') ?></div>
            <div id="explainCVC" style="display: block;">
                <table border="0" width="100%" cellspacing="4" cellpadding="4">
                    <tr>
                        <td>
                            <img src="<?php echo $this->getSkinUrl('images/epay/cvc_dk.gif') ?>" border="0" title="<?php echo $this->__('EPAY_LABEL_37') ?>" />&nbsp;&nbsp;
                        </td>
                        <td width="10">&nbsp;</td>
                        <td>
                            <img src="<?php echo $this->getSkinUrl('images/epay/cvc_master.gif') ?>" border="0" title="<?php echo $this->__('EPAY_LABEL_38') ?>" />&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td><div style="color:#888888; font-size: 12px;"><?php echo $this->__('EPAY_LABEL_15') ?></div></td>
                        <td width="10">&nbsp;</td>
                        <td><div style="color:#888888; font-size: 12px;"><?php echo $this->__('EPAY_LABEL_16') ?></div></td>
                    </tr>
                </table>
            </div>
        </div>
	</div>
	
	<div id="paymenttype-17" style="display:<?php echo (!$paymentTypeFound && ($paymentTypeFound = paymentTypeEnabled(17, $order))) ? 'block' : 'none'; ?>;">
		<!-- EWIRE -->
		<table border="0" width="100%" cellspacing="4" cellpadding="4">
			<tr>
				<td style="width: 180px;">
				<?php echo $this->__('EPAY_LABEL_83') . "&nbsp;'" . $this->__('EPAY_LABEL_17') . "'&nbsp;" . $this->__('EPAY_LABEL_84'); ?><br /><br />
				<b><?php echo $this->__('EPAY_LABEL_85') ?></b><br />
				<?php echo $this->__('EPAY_LABEL_86'); ?>
				</td>
				<td valign="top">
					<input type="image" src="<?php echo $this->getSkinUrl('images/epay/ewire_35.gif') ?>">
				</td>
			</tr>
		</table>	
	</div>
	
	<div id="paymenttype-20" style="display:<?php echo (($paymentTypeFound = paymentTypeEnabled(20, $order)) && !$paymentTypeFound) ? 'block' : 'none'; ?>;">
		<!-- eDankort -->
		<table border="0" width="100%" cellspacing="4" cellpadding="4">
			<tr>
				<td style="width: 180px;">
				<?php echo $this->__('EPAY_LABEL_83') . "&nbsp;'" . $this->__('EPAY_LABEL_17') . "'&nbsp;" . $this->__('EPAY_LABEL_87'); ?><br /><br /> 
				<b><?php echo $this->__('EPAY_LABEL_85') ?></b><br />
				<?php echo $this->__('EPAY_LABEL_88'); ?>
				</td>
				<td valign="top">
					<input type="image" src="<?php echo $this->getSkinUrl('images/epay/edankort_35.gif') ?>">
				</td>
			</tr>
		</table>
	</div>
	
	<div id="paymenttype-21" style="display:<?php echo (!$paymentTypeFound && ($paymentTypeFound = paymentTypeEnabled(21, $order))) ? 'block' : 'none'; ?>;">
		<!-- Nordea -->
		<table border="0" width="100%" cellspacing="4" cellpadding="4">
			<tr>
				<td style="width: 180px;">					
					<?php echo $this->__('EPAY_LABEL_83') . "&nbsp;'" . $this->__('EPAY_LABEL_17') . "'&nbsp;" . $this->__('EPAY_LABEL_89'); ?>
					<b><?php echo $this->__('EPAY_LABEL_85') ?></b><br />
					<?php echo $this->__('EPAY_LABEL_88'); ?>
				</td>
				<td valign="top">
					<input type="image" src="<?php echo $this->getSkinUrl('images/epay/nordea_35.gif') ?>">
				</td>
			</tr>
		</table>
	</div>
	
	<div id="paymenttype-22" style="display:<?php echo (!$paymentTypeFound && ($paymentTypeFound = paymentTypeEnabled(22, $order))) ? 'block' : 'none'; ?>;">
		<!-- Danske Bank -->
		<table border="0" width="100%" cellspacing="4" cellpadding="4">
			<tr>
				<td style="width: 180px;">
					<?php echo $this->__('EPAY_LABEL_83') . "&nbsp;'" . $this->__('EPAY_LABEL_17') . "'&nbsp;" . $this->__('EPAY_LABEL_90'); ?><br><br>
					<b><?php echo $this->__('EPAY_LABEL_85') ?></b><br />
					<?php echo $this->__('EPAY_LABEL_88'); ?>
				</td>
				<td valign="top">
					<input type="image" src="<?php echo $this->getSkinUrl('images/epay/danske_22.gif') ?>">
				</td>
			</tr>
		</table>
	</div>
		
<?php
	if ($standard->getConfigData('description', $order ? $order->getStoreId() : null) == "1") {
?>	
	<table border="0" width="100%" cellspacing="4" cellpadding="4">
		<tr>
			<td style="width: 180px;">
				<label name="CommentHeader"><?php echo $this->__('EPAY_LABEL_72') ?> :</label>
			</td>
			<td>
				<textarea name="description" id="description" rows="4" cols="50" class="required-entry input-text"></textarea>
	  	</td>
	  </tr>
	</table>
<?php
	}
?>			
	<table border="0" width="100%" cellspacing="4" cellpadding="4">
		<tr>
			<td style="width: 180px;">&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td style="width: 180px;">&nbsp;</td>
			<td>
                <button  name="paymentSubmit" id="paymentSubmit" onclick="epayCCForm.submit(this);" class="button btn-checkout form-button-alt" title="<?php echo $this->__('EPAY_LABEL_17') ?>"><span><span><?php echo $this->__('EPAY_LABEL_17') ?></span></span></button>
                <script type="text/javascript">
                    //<![CDATA[
                    var epayCCForm = new VarienForm('epay');
                    epayCCForm.submit = function(button) { this.validator.validate(); }.bind(epayCCForm);
                    //]]>
                </script>
			</td>
		</tr>
	</table>

	<input type="hidden" name="merchantnumber" value="<?php echo $standard->getConfigData("merchantnumber", $order ? $order->getStoreId() : null) ?>">
	<input type="hidden" name="accepturl" value="<?php echo Mage::getUrl('epay/standard/success') ?>">
	<input type="hidden" name="declineurl" value="<?php echo Mage::getUrl('epay/standard/redirect') . "?forcerelay=1"; ?>">
	<input type="hidden" name="callbackurl" value="<?php echo Mage::getUrl('epay/standard/callback') ?>">
	<input type="hidden" name="orderid" value="<?php echo $standard->getCheckout()->getLastRealOrderId() ?>">
	<input type="hidden" name="authmail" value="<?php echo $standard->getConfigData('authmail', $order ? $order->getStoreId() : null) ?>">
	<input type="hidden" name="authsms" value="<?php echo $standard->getConfigData('authsms', $order ? $order->getStoreId() : null) ?>">
	<input type="hidden" name="instantcapture" value="<?php echo $standard->getConfigData('instantcapture', $order ? $order->getStoreId() : null) ?>">
	<input type="hidden" name="group" value="<?php echo $standard->getConfigData('group', $order ? $order->getStoreId() : null) ?>">
	<input type="hidden" name="amount" value="<?php echo ((float)$order->getBaseTotalDue()) * 100 ?>">
	<input type="hidden" name="MD5Key" value="<?php echo $standard->calcMd5Key($order) ?>">
	<input type="hidden" name="currency" value="<?php echo $standard->convertToEpayCurrency($order->getBaseCurrency()->getCode()) ?>">
	<input type="hidden" name="splitpayment" value="<?php echo $standard->getConfigData('splitpayment', $order ? $order->getStoreId() : null) ?>">
	<input type="hidden" name="transfee" value="0">
	<input type="hidden" name="language" value="<?php echo $standard->calcLanguage(Mage::app()->getLocale()->getLocaleCode()) ?>">
	<input type="hidden" name="HTTP_COOKIE" value="<?php echo getenv("HTTP_COOKIE"); ?>">
	<input type="hidden" name="instantcallback" value="1">
	<input type="hidden" name="httpaccepturl" value="0">
	<input type="hidden" name="redirectmethod" value="POST">
	<input type="hidden" name="cms" value="magento">
</form>

<!--
Fix replacing urls with the shop-urls
-->
<script type="text/javascript" src="https://relay.ditonlinebetalingssystem.dk/relay/v2/replace_relay_urls.js"></script>