<?php
$_item = $this->getItem();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);

$showDrink = $showTypeMenus = $showTypeExtras =false;
$product = Mage::getModel('catalog/product')->load($_item->getProductId());

$_composition_form = false;

try {
	if ($product->getTypeId() == 'simple') {
		$_composition_form = (int)$product->getData('compositionform');
		$productSimpleSKU = explode("-", $product->getSku());
		$categoryIds = $product->getCategoryIds();
		if (is_array($categoryIds)) $categoryIdEnd = end($categoryIds);
		else $categoryIdEnd = null;
		if ($productSimpleSKU[0] == "drinks") $showDrink = true;
		//elseif ($productSimpleSKU[0] == "extras") $showTypeExtras = true;
	} else {
		$productBundleSKU = $product->getSku();
		$aProductBundleSKU = explode("-", $product->getSku());
		if (in_array($productBundleSKU, array('valgfrisupermenu', 'supermenu', 'saladmenu', 'menu', 'kidsmenu'))) $showTypeMenus = true;
		elseif ($aProductBundleSKU[0] == 'extras') $showTypeExtras = true;
	}
} catch (Exception $e) {
	Mage::log($e->getMessage());
}


// serial number of a product in the basket shown on the basket page (see cart.phtml)
global $prodNo;
?>
<div class="order_position">
  <div class="ll"><?php echo $prodNo ?></div>
  <div class="lc">
	  <?php
	  // show "type" for menus
	  if ($showTypeMenus) {
	  ?>
		<span class="fill"><?php echo $this->__('Type of Menus') ?></span>:&nbsp;
		<span class="chosen"><?php echo $this->htmlEscape($product->getName()) ?></span>
	  <?php 
		$showTypeMenus = false;
	  }
	  if ($showTypeExtras) {
	  ?>
		<span class="fill"><?php echo Mage::helper("productview")->__('Type of Extras') ?></span>:&nbsp;
		<span class="chosen"><?php echo $this->htmlEscape($product->getName()) ?></span>
	  <?php 
		$showTypeExtras = false;
	  }
	  ?>
     <?php $_options = $this->getOptionList(); ?>
     <?php if ($_options): ?>
      <?php foreach ($_options as $_option) : ?>
        <span class="fill"><?php echo $this->htmlEscape($_option['label']) ?></span>:&nbsp;<?php if (is_array($_option['value'])) :
		  $_aOptionName = array();
		  $showSizeSubs = false;
		  $i = 0;
            foreach ($_option['value'] as $val) :
				$i++;
				$_aOptionName[$i] = $val['name'];
				$valSKUs = explode("-", $val['sku']);
				if ($productBundleSKU == 'subs' && $valSKUs[0] == 'subs') $showSizeSubs = true;
				elseif ($valSKUs[0] == 'drinks') {
					if (is_array($val['category_ids'])) $categoryId = end($val['category_ids']);
					else $categoryId = null;
					$_aOptionName[$i] .= " (" . $this->htmlEscape(Mage::getModel("catalog/category")->load($categoryId)->getName()) . ")" ;
				}
            endforeach;
          endif;
		  ?><span class="chosen"><?php echo implode(', ', $_aOptionName); ?></span>
	  <?php
	  // show "size" for subs
	  if ($showSizeSubs) {
		if (is_array($val['category_ids'])) $categoryId = end($val['category_ids']);
		else $categoryId = null;
	  ?>
		<span class="fill"><?php echo $this->__('Size') ?></span>:&nbsp;
		<span class="chosen"><?php echo $this->htmlEscape(Mage::getModel("catalog/category")->load($categoryId)->getName()) ?></span>
	  <?php 
		$showSizeSubs = false;
	  }
	  ?>
      <?php endforeach; ?>
     <?php else: ?>
	 <?php 
	  // show "size" for simple product for drinks
	  if ($showDrink) {
	  ?>
		<span class="fill"><?php echo $this->__('Type') ?></span>:
		<span class="chosen"><?php echo $this->htmlEscape($_item->getProduct()->getName()) . 
				" (" . $this->htmlEscape(Mage::getModel("catalog/category")->load($categoryIdEnd)->getName()) . ")" ?></span>
	  <?php 
		  $showDrink = false;
	  } else {
		if (!$_composition_form) {
		?>
			<span class="fill"><?php echo $this->__('Type') ?></span>:
			<span class="chosen"><?php echo $this->htmlEscape($_item->getProduct()->getName()) ?></span>
		<?php
		} else {
			?>
				<span class="fill"><?php echo $this->htmlEscape($_item->getProduct()->getName()) ?></span>
				<span class="chosen"><?php echo $this->htmlEscape($_item->getProduct()->getDescription()) ?></span>
			<?php
		}}
	  ?>
     <?php endif;?>
    <p>
      <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
      <span class="fill">*</span>&nbsp; <span class="chosen"><?php echo $message['text'] ?></span>
        <?php endforeach; ?>
      <?php endif; ?>
    </p>
    <p>
      <?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
          <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
      <?php endif;?>      
    </p>
  </div>
  <div class="lr">
    <div class="amount">
      <?php echo Mage::helper("productview")->__('Amount') ?>
      <?php echo $this->getQty() ?>
    </div>
    <div class="price"><?php echo $this->__('PRICE') ?>

 <?php if ($canApplyMsrp): ?>
    <span class="cart-price">
        <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
        <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
        <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
        <script type="text/javascript">
            Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
        </script>
    </span>
    <?php else: ?>

      <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
      
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
          <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
        <?php endif; ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
          <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
        <?php else: ?>
          <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
        <?php endif; ?>

        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

          <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                  <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
              <?php endforeach; ?>
            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
              <?php endforeach; ?>
            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
              <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
              <?php endforeach; ?>
            <?php endif; ?>
          </div>

          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
              <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
            </div>
          <?php endif; ?>
        <?php endif; ?>
      <?php endif; ?>
            
      <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
          <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
          <span class="cart-price">
        <?php endif; ?>

        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
        <?php else: ?>
            <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
        <?php endif; ?>

          </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

          <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
            <?php endforeach; ?>
          <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
            <?php endforeach; ?>
          <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
            <?php endforeach; ?>
          <?php endif; ?>
          </div>

          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
          <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
          </div>
          <?php endif; ?>
        <?php endif; ?>
      <?php endif; ?>
    <?php endif; ?>

    </div>
  </div>
</div>