<form id="co-billing-form" action="">
<fieldset style="border: none; padding: 25px 15px 0;">
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
        <li class="wide">
            <h3><?php echo Mage::helper('productview')->__('Delivery data:'); ?></h3>

            <?php if($addressArray = $this->getAddressArray()) : ?>
                <div class="lblock"><?php echo Mage::helper('productview')->__('Name'); ?></div><span class="rblock"><?php echo $addressArray['name']; ?></span>
                <div class="lblock"><?php echo Mage::helper('productview')->__('Telephone'); ?></div><span class="rblock"><?php echo $addressArray['telephone']; ?></span>
                <div class="lblock"><?php echo Mage::helper('productview')->__('Street'); ?></div><span class="rblock"><?php echo $addressArray['street']; ?></span>
                <div class="lblock"><?php echo Mage::helper('productview')->__('Postcode'); ?></div><span class="rblock"><?php echo $addressArray['postcode']; ?></span>
                <div class="lblock"><?php echo Mage::helper('productview')->__('City'); ?></div><span class="rblock"><?php echo $addressArray['city']; ?></span>
            <?php endif; ?>

            <input type="hidden" class="address-select" id="billing-address-select" name="billing_address_id" value="<?php echo $this->getAddress()->getId(); ?>" />
            <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" />
        </li>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <fieldset style="border:none;">
            <input type="hidden" name="billing[address_id]" id="billing:address_id" value="<?php echo $this->getAddress()->getId() ?>" />
            <input type="hidden" name="billing[country_id]" id="billing:country_id" value="DK" />

            <input type="hidden" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1" />

            <ul>
                <li class="fields">
					<div class="field">
						<label for="billing:company"><?php echo Mage::helper('productview')->__('Company') ?></label>
						<div class="input-box">
							<input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo Mage::helper('productview')->__('Company') ?>" class="input-text" />
						</div>
					</div>
                </li>
				<li class="fields">
					<div class="field">
						<label for="billing:cvr"><?php echo Mage::helper('productview')->__('CVR') ?></label>
						<div class="input-box">
							<input type="text" id="billing:cvr" name="billing[cvr]" value="<?php echo $this->htmlEscape($this->getAddress()->getCvr()) ?>" title="<?php echo Mage::helper('productview')->__('CVR') ?>" class="input-text" />
						</div>
					</div>
				</li>
                <li class="fields">
					<div class="field">
						<label for="billing:firstname" class="required"><?php echo Mage::helper('productview')->__('Name') ?></label>
						<div class="input-box">
							<input type="text" class="input-text required-entry" title="Name" value="" name="billing[firstname]" id="billing:firstname">
						</div><em>*</em>
					</div>
                </li>
				<li class="fields">
					<div class="field">
						<label for="billing:street1" class="required"><?php echo Mage::helper('productview')->__('Address') ?></label>
						<div class="input-box">
							<input type="text" title="<?php echo Mage::helper('productview')->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" />
						</div><em>*</em>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label for="billing:postcode" class="required"><?php echo Mage::helper('productview')->__('Postcode') ?></label>
						<div class="input-box">
							<input type="text" title="<?php echo Mage::helper('productview')->__('Postcode') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="zip input-text validate-zip-international required-entry" />
						</div><em>*</em>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label for="billing:city" class="required"><?php echo Mage::helper('productview')->__('City') ?></label>
						<div class="input-box">
							<input type="text" title="<?php echo Mage::helper('productview')->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="city input-text required-entry" id="billing:city" />
						</div><em>*</em>
					</div>
				</li>
				<li class="fields">
                    <div class="field">
                        <label for="billing:telephone" class="required"><?php echo Mage::helper('productview')->__('Mobiltelefon') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('productview')->__('Mobiltelefon') ?>" class="required-entry validate-mobilephone8" maxlength="8" id="billing:telephone" />
                        </div><em>*</em>
						<div style="float:left;margin-left:20px;width:450px;font-size:85%;"><?php echo Mage::helper('productview')->__('Please, indicate your 8-digit mobile phone number, so we can send you a final confirmation of your order by SMS.') ?></div>
                    </div>
                    <?php /*
					<div class="field">
                        <label for="billing:fax"><?php echo Mage::helper('productview')->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo Mage::helper('productview')->__('Fax') ?>" class="input-text" id="billing:fax" />
                        </div>
                    </div>
					*/
					?>
                </li>
				<?php if(!$this->isCustomerLoggedIn()): ?>
				<li class="fields">
					<div class="field">
						<label for="billing:email" class="required"><?php echo Mage::helper('productview')->__('Email Address') ?></label>
						<div class="input-box">
							<input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo Mage::helper('productview')->__('Email Address') ?>" class="rblock email validate-email required-entry" />
						</div><em>*</em>
					</div>
                    <div class="field" style="float: left;">
                        <label for="billing:email_confirm" class="required"><?php echo Mage::helper('productview')->__('Repeat email') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[email_confirm]" id="billing:email_confirm" title="" value="<?php echo $this->getAddress()->getEmailConfirm() ?>" class="rblock email validate-email-confirm required-entry"  />
                        </div>
                        <em>*</em>
                    </div>
				</li>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                <li class="fields">
                <?php if ($_dob->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                <?php endif; ?>
                <?php if ($_gender->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                <?php endif ?>
                </li>
            <?php endif ?>

            <?php if ($this->isTaxvatEnabled()):?>
                <li><?php echo $this->getTaxvatHtml() ?></li>
            <?php endif; ?>

                <li class="fields" id="register-customer-password">
                    <div class="field">
                        <label for="billing:customer_password" class="required"><?php echo Mage::helper('productview')->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo Mage::helper('productview')->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div><em>*</em>
                    </div>
                    <div class="field" style="float: left;">
                        <label for="billing:confirm_password" class="required"><?php echo Mage::helper('productview')->__('Repeat password') ?></label>
                        <div class="input-box">
                            <input type="password" name="billing[confirm_password]" title="<?php echo Mage::helper('productview')->__('Repeat password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                        </div><em>*</em>
                    </div>
                </li>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                <?php endif; ?>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="control">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo Mage::helper('productview')->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </fieldset>
     </li>

     <li class="fields">
        <div class="field">
            <label for="billing:caldate" class="required"><?php echo $this->__('Delivery date') ?></label>
            <div class="input-box">
                <input type="text" readonly="readonly" name="billing[caldate]" id="billing:caldate" value="<?php echo strftime('%d-%m-%Y %H:%M', Mage::getModel('core/date')->timestamp(time()+3600)); //!!!compensate magento time shift and add 1 hr to delivery time ?>" class="input-text no-changes" style="width:230px; margin-right:3px;" />
                <img title="<?php echo $this->__('Delivery date') ?>" id="cal_date_trig" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/submarine/default/images/calendar-icon.png'; ?>"  class="v-middle"/>
                <script type="text/javascript">// <![CDATA[

                Translator.add(
                    'Please use date in the future between 10 a.m. and 9.30 p.m.',
                    '<?php echo $this->__('Please use date in the future between 10 a.m. and 9.30 p.m.') ?>'
                );
                Translator.add(
                    'Please, indicate your 8-digit mobile phone number, so we can send you a final confirmation of your order by SMS.',
                    '<?php echo $this->__('Please, indicate your 8-digit mobile phone number, so we can send you a final confirmation of your order by SMS.')?>'
                );
                Translator.add(
                    'Please make sure your email address match.',
                    '<?php echo $this->__('Please make sure your email address match.')?>'
                );
                    var onUpdate = function(params) {

                        var dateFrom = Date.parse(params.date.getDate()+'/'+params.date.getMonth()+1+'/'+params.date.getFullYear()+' 10:00:00'),
                            dateCurrent = Date.parse(params.date.getDate()+'/'+params.date.getMonth()+1+'/'+params.date.getFullYear()+' '+params.date.getHours()+':'+params.date.getMinutes()+':00'),
                            dateTo = Date.parse(params.date.getDate()+'/'+params.date.getMonth()+1+'/'+params.date.getFullYear()+' 21:30:00');

                        if ((dateFrom > dateCurrent) || (dateCurrent > dateTo)) {
                            $('billing:caldate').addClassName('validation-failed');
                            $('billing:caldate').addClassName('validate-date');
                            return false;

                        }
                        $('billing:caldate').removeClassName('validation-failed');
                        $('billing:caldate').removeClassName('validate-date');
                        ($('advice-validate-date-billing:caldate') != undefined) ? $('advice-validate-date-billing:caldate').remove() : 0;
                        return true;
                    };

                    Calendar.setup({
                        firstDay : 1,
                        showsTime : true,
                        inputField : 'billing:caldate',
                        ifFormat : '%e-%m-%Y %H:%M',
                        button : 'cal_date_trig',
                        align : 'Bl',
                        weekNumbers : false,
                        range : ['2015', '2020'],//!!!
                        singleClick : true,
                        onUpdate: onUpdate
                    });

                    onUpdate({
                        date: new Date($('billing:caldate').getValue().replace(/-/g,'/'))
                    });
                // ]]>
                </script>
            </div><em>*</em>
            <div style="float:left;margin-left:20px;width:450px;font-size:85%;"><?php echo $this->__('Please use date in the future between 10 a.m. and 9.30 p.m.') ?></div>
        </div>
     </li>
    </ul>

    <div class="buttons-set" id="billing-buttons-container">
        <div class="field"><em>*</em>&nbsp;<?php echo Mage::helper('productview')->__('Required Fields'); ?></div>
        <button type="button" title="<?php echo Mage::helper('productview')->__('Continue') ?>" class="button" onclick="billing.save();"><span><span><?php echo Mage::helper('productview')->__('Continue') ?></span></span></button>
        <span class="please-wait" id="billing-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</fieldset>
</form>
<script type="text/javascript">
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');
//]]>
</script>
