<div class="content orderview" style="margin-left:15px; padding-bottom:0px !important;">
    <div class="col-set order-info-box">
        <div class="col">
            <div class="box">
                <div class="box-title">
                    <div class="title"><?php echo Mage::helper('productview')->__('Delivery date') ?></div>
                </div>
                <div class="box-content">
                    <?php
                    $custom = $this->getCustomVars();
                    foreach($custom as $key => $value){
                        ?>
                        <?php echo $value;?> <br/>
                        <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
