
<?php #echo $this->helper('core/js')->includeScript('prototype/prototype.js') ?>
<?php #echo $this->helper('core/js')->includeScript('prototype/validation.js') ?>
<?php #echo $this->helper('core/js')->includeScript('varien/js.js') ?>
<?php #echo $this->helper('core/js')->includeScript('varien/product.js') ?>
<?php #echo $this->helper('core/js')->includeScript('varien/configurable.js') ?>
<?php #echo $this->helper('core/js')->includeScript('varien/form.js') ?>

<?php #echo $this->helper('core/js')->includeSkinScript('js/jquery-1.7.1.min.js') ?>
<?php #echo $this->helper('core/js')->includeSkinScript('js/noconflict.js') ?>
<?php #echo $this->helper('core/js')->includeSkinScript('js/product.js') ?>
<?php #echo $this->helper('core/js')->includeSkinScript('js/bundle.js') ?>


<?php echo $this->getChildHtml('content') ?>
